DROP SCHEMA IF EXISTS Food_Truck;
CREATE SCHEMA IF NOT EXISTS Food_Truck;

USE Food_Truck;
DROP TABLE IF EXISTS ORDERITENS;
DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS USERS; 
DROP TABLE IF EXISTS CUSTOMERS; 

CREATE TABLE CUSTOMERS (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(200) NOT NULL,
   EMAIL VARCHAR(200) NOT NULL,
   ADDRESS VARCHAR(200) NOT NULL,
   PRIMARY KEY (ID) 
);

CREATE TABLE USERS (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   NAME VARCHAR(200) NOT NULL,
   EMAIL VARCHAR(200) NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE PRODUCTS (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   DESCRIPTION VARCHAR(500) NOT NULL,
   PRICE DECIMAL NOT NULL,
   PRIMARY KEY (ID)
);

CREATE TABLE ORDERS (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   CUSTOMERID BIGINT,
   SELLERID BIGINT,
   ORDERDATE DATETIME,
   PREPAREDDATE DATETIME,
   DELIVERYDATE DATETIME,
   PRIMARY KEY (ID),
   FOREIGN KEY (CUSTOMERID) REFERENCES CUSTOMERS(ID),
   FOREIGN KEY (SELLERID) REFERENCES USERS(ID)
);

CREATE TABLE ORDERITENS (
   ID BIGINT NOT NULL AUTO_INCREMENT,
   QUANTITY DECIMAL,
   UNITPRICE DECIMAL,
   PRODUCTID BIGINT,
   ORDERID BIGINT,
   PRIMARY KEY (ID),
   FOREIGN KEY (PRODUCTID) REFERENCES PRODUCTS(ID),
   FOREIGN KEY (ORDERID) REFERENCES ORDERS(ID)
);

/*COLOCANDO DADOS*/
INSERT INTO USERS(NAME,EMAIL) VALUES("Dayan","dayan@gmail.com");
INSERT INTO USERS(NAME,EMAIL) VALUES("Helena","helena@gmail.com");
INSERT INTO USERS(NAME,EMAIL) VALUES("Calebe","calebe@gmail.com");
INSERT INTO USERS(NAME,EMAIL) VALUES("Nelson","nelson@gmail.com");


INSERT INTO PRODUCTS (DESCRIPTION,PRICE) VALUES("Batata Frita",5);
INSERT INTO PRODUCTS (DESCRIPTION,PRICE) VALUES("X-Hamburguer",8);
INSERT INTO PRODUCTS (DESCRIPTION,PRICE) VALUES("X-Bacon",10);
INSERT INTO PRODUCTS (DESCRIPTION,PRICE) VALUES("X-Salada",10);
INSERT INTO PRODUCTS (DESCRIPTION,PRICE) VALUES("Refrigerante Lata",5);
